services:
    mysql:
        image: mysql:latest
        container_name: mysql_container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
